// Shared types for backend and frontend (Entities, DTOs)
//
// This file is intentionally derived from the *database entity types* generated by Supabase
// (`src/db/database.types.ts`) so API DTOs remain consistent with the schema.

import type { Tables } from "./db/database.types";

/**
 * Core DB entity types (Row shapes).
 * Using aliases keeps DTO definitions readable while still being schema-derived.
 */
export type CardEntity = Tables<"cards">;
export type AiGenerationRequestEntity = Tables<"ai_generation_requests">;
export type AiProposalLogEntity = Tables<"ai_proposal_logs">;

/**
 * Brand-ish alias used across API DTOs.
 * NOTE: In DB it is a uuid stored as string.
 */
export type Uuid = string;

/**
 * DB timestamps are serialized as ISO strings by Supabase.
 * We keep them as strings in REST DTOs.
 */
export type IsoDateTimeString = string;

/**
 * API-level enums (narrowed from DB text columns).
 * DB uses CHECK constraints but the generated types are `string`, so we narrow them here.
 */
export type CardOrigin = "manual" | "ai";
export type AiGenerationStatus = "success" | "failure";

/**
 * Helper: rename DB snake_case timestamps to API camelCase.
 */
export type ApiTimestamps = {
  createdAt: IsoDateTimeString;
  updatedAt: IsoDateTimeString;
};

/**
 * Helper: common paginated response envelope.
 */
export type PaginatedResponse<TItem> = {
  data: TItem[];
  page: number;
  pageSize: number;
  total: number;
};

/**
 * Public API error codes (per `doc/api_plan.md`).
 * Keep this in sync with the REST contract.
 */
export type ApiErrorCode =
  | "AUTH_REQUIRED"
  | "VALIDATION_ERROR"
  | "INVALID_PAGINATION"
  | "INVALID_SORT"
  | "CARD_NOT_FOUND"
  | "GENERATION_NOT_FOUND"
  | "INVALID_REVIEW_TOKEN"
  | "PROPOSAL_ALREADY_DECIDED"
  | "DAILY_GENERATION_LIMIT_REACHED"
  | "DAILY_AI_ACCEPT_LIMIT_REACHED"
  | "AI_GENERATION_FAILED"
  | "INTERNAL_ERROR";

/**
 * Helper: consistent API error shape (per `doc/api_plan.md`).
 */
export type ApiErrorDto = {
  error: {
    code: ApiErrorCode;
    message: string;
    details?: Record<string, unknown>;
  };
};

// -----------------------------
// Cards DTOs + Commands
// -----------------------------

/**
 * Card DTO returned by API.
 * Derived from `public.cards` entity, with naming aligned to the REST plan.
 */
export type CardDto = Pick<CardEntity, "id" | "front" | "back"> & {
  origin: CardOrigin;
  aiGenerationId: CardEntity["ai_generation_id"];
} & ApiTimestamps;

/** Command: create manual card (`POST /api/cards`). */
export type CreateManualCardCommand = Pick<CardEntity, "front" | "back">;

/** Command: update card (`PATCH /api/cards/{cardId}`). */
export type UpdateCardCommand = Partial<Pick<CardEntity, "front" | "back">>;

/** Response wrapper: list cards (`GET /api/cards`). */
export type ListCardsResponseDto = PaginatedResponse<CardDto>;

/** Response: delete card (`DELETE /api/cards/{cardId}`). */
export type DeleteCardResponseDto = { ok: true };

// -----------------------------
// Limits DTOs
// -----------------------------

export type LimitStatsDto = {
  limit: number;
  used: number;
  remaining: number;
};

/** Response: today limits (`GET /api/limits/today`). */
export type TodayLimitsDto = {
  timezone: "UTC";
  resetAt: IsoDateTimeString;
  generationRequests: LimitStatsDto;
  aiAcceptedCards: LimitStatsDto;
};

// -----------------------------
// AI generation flow DTOs + Commands
// -----------------------------

/**
 * Proposal payload returned by generation.
 * Not persisted in DB by design.
 */
export type AiCardProposalDto = {
  proposalIndex: number;
  front: CardEntity["front"];
  back: CardEntity["back"];
};

/** Command: start AI generation (`POST /api/ai/generations`). */
export type StartAiGenerationCommand = {
  inputText: string;
  requestedCardsCount: AiGenerationRequestEntity["requested_cards_count"];
};

export type AiInlineLimitsDto = {
  generationRequestsRemaining: number;
  aiAcceptedCardsRemaining: number;
  resetAt: IsoDateTimeString;
};

export type AiProposalLogDto = {
  generationId: AiProposalLogEntity["generation_id"];
  proposalIndex: AiProposalLogEntity["proposal_index"];
  accepted: AiProposalLogEntity["accepted"];
  createdCardId: AiProposalLogEntity["created_card_id"];
  createdAt: AiProposalLogEntity["created_at"];
};

/** Success response: start AI generation. */
export type StartAiGenerationSuccessDto = {
  ok: true;
  generationId: AiGenerationRequestEntity["generation_id"];
  reviewToken: string;
  proposals: AiCardProposalDto[];
  limits: AiInlineLimitsDto;
};

/** Failure response: start AI generation (still returns `generationId` + limits). */
export type StartAiGenerationFailureDto = {
  ok: false;
  generationId: AiGenerationRequestEntity["generation_id"];
  error: ApiErrorDto["error"] & {
    details?: {
      provider?: AiGenerationRequestEntity["provider"];
      model?: AiGenerationRequestEntity["model"];
    };
  };
  limits: AiInlineLimitsDto;
};

/** Union: start AI generation response. */
export type StartAiGenerationResponseDto = StartAiGenerationSuccessDto | StartAiGenerationFailureDto;

/** Command: accept proposal (`POST /api/ai/generations/{generationId}/proposals/{proposalIndex}/accept`). */
export type AcceptAiProposalCommand = Pick<CardEntity, "front" | "back"> & {
  reviewToken: string;
};

/** Command: reject proposal (`POST /api/ai/generations/{generationId}/proposals/{proposalIndex}/reject`). */
export type RejectAiProposalCommand = {
  reviewToken: string;
};

/** Response: reject proposal. */
export type RejectAiProposalResponseDto = {
  ok: true;
  log: AiProposalLogDto;
};

/** Response: accept proposal. */
export type AcceptAiProposalResponseDto = {
  card: CardDto;
  log: {
    generationId: AiProposalLogEntity["generation_id"];
    proposalIndex: AiProposalLogEntity["proposal_index"];
    accepted: true;
    createdCardId: NonNullable<AiProposalLogEntity["created_card_id"]>;
    createdAt: AiProposalLogEntity["created_at"];
  };
  limits: {
    aiAcceptedCardsRemaining: number;
    resetAt: IsoDateTimeString;
  };
};

// -----------------------------
// AI generation logs (optional read-only endpoints)
// -----------------------------

/** Response: get generation log (`GET /api/ai/generations/{generationId}`). */
export type AiGenerationLogDto = {
  generationId: AiGenerationRequestEntity["generation_id"];
  status: AiGenerationStatus;
  inputLength: AiGenerationRequestEntity["input_length"];
  requestedCardsCount: AiGenerationRequestEntity["requested_cards_count"];
  generatedCardsCount: NonNullable<AiGenerationRequestEntity["generated_cards_count"]>;
  provider: AiGenerationRequestEntity["provider"];
  model: AiGenerationRequestEntity["model"];
  createdAt: AiGenerationRequestEntity["created_at"];
};

/** Item: generation history list. */
export type AiGenerationHistoryItemDto = {
  generationId: AiGenerationRequestEntity["generation_id"];
  status: AiGenerationStatus;
  requestedCardsCount: AiGenerationRequestEntity["requested_cards_count"];
  generatedCardsCount: AiGenerationRequestEntity["generated_cards_count"];
  createdAt: AiGenerationRequestEntity["created_at"];
};

/** Response: list generation history (`GET /api/ai/generations`). */
export type ListAiGenerationsResponseDto = PaginatedResponse<AiGenerationHistoryItemDto>;

// -----------------------------
// Metrics / KPI DTOs (optional)
// -----------------------------

export type KpiMetricDto = {
  name: string;
  value: number;
};

export type Kpi1AcceptanceRateDto = KpiMetricDto & {
  accepted: number;
  generated: number;
};

export type Kpi2AiShareOfCreatedCardsDto = KpiMetricDto & {
  aiCards: number;
  allCards: number;
};

/** Response: KPI summary (`GET /api/metrics/kpi`). */
export type KpiSummaryDto = {
  kpi1: Kpi1AcceptanceRateDto;
  kpi2: Kpi2AiShareOfCreatedCardsDto;
};
